name: Check Code with Black

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install Black
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      # Run Black on the ./backend directory
      - name: Run Black
        run: |
          black --check ./backend
